/*




                                            ABSTRUCTION

ABSTRUCTION IS THE PROCESS OF HIDING THE IMPLEMENTATION DETAILS AND SHOWING ONLY FUNCTIONALITY TO USER

HOW TO ACHIEVE ABSTRACTION?
>> THERE ARE TWO WAYS TO ACHIEVE ABSTRACTION IN JAVA
   1)ABSTRACTION CLASS (0 TO 100%)
   2)INTERFACE (ACHIEVE 100% ABSTRACTION)

DECLARATION :
>> TO DECLARE A CLASS AS AN ABSTRACT CLASS, WE NEED TO ADD ABSTRACT KEYWORD BEFORE THE CLASS

EXAMPLE :
        ABSTRACT CLASS MOBILE USER{


        }


ABSTRACT MRTHOD :
        ABSTRACT METHOD IS DIFFERENT FROM NORMAL METHOD. IT DO NOT CONTAINS CURLY BRACES.
 
EXAMPLE :
        ABSTRACT VOID MESSAGE();



POINTS TO BE REMEMBERD:
      >> ABSTRACTION METHOD HAS NO BODY
      >> IT MUST BE END UP WITH A SEMICOLON
      >> IT MUST BE IN THE ABSTRACT CLASS
      >> IT MUST BE OVERRIDDEN
      >> IT CAN NOT BE FINAL AND STATIC


      >> ABSTRACT CLASS CAN HAVE ABSTRACT AND NON ABSTRACT METHOD 
         BUT NON ABSTRACT CLASS CAN'T HAVE ABSTRACT METHOD




SOME MORE POINTS ABOUT ABTRACTION:
     >> ABSTRACT CLASS CAN'T BE INSTANTIATED(OBJECT CAN NOT BE CREATED)
     >> IF YOU EXTEND AN ABSTRACT CLASS YOU HAVE TO USE ALL IT'S ABSTRACT METHOD
        OR YOU HAVE TO DECLARE THE CLASS ABSTRACT ITSELF
     



*/