package Constructor;



/*

CONSTRUCTOR IS A SPECIAL TYPE OF METHOD THAT IS USED TO INITIALIZE THE OBJECT


PROPERTIES ARE :
1.CONSTRUCTOR HAS THE SAME NAME ASS THAT OF THE CLASSS IT BELONGS
2.CONSTRUCTOR IS A SPECIAL TYPE OF METHOD
3.IT IS CALLED AUTOMATICALLY
4.CONSTRUCTOR CAN BE DEFAULT AND PARAMETERIZED

*/