package Static;







/*
                                STATIC METHOD


RESTRICTIONS OF STATIC METHOD
    1. STATIC METHOD CAN'T USE NON STATIC MEMBER
    2."THIS" AND "SUPER" KEYWORD CAN'T BE USED HERE
    3.STATIC METHOD IS CONNECTED WITH CLASS NOT OBJECT .iT DEALS WITH CLASSES.
    



*/