
/*

                                             POLYMORPHISM
 POLY AND MORPHS AREV2 GREEK WORDS
               POLY MEANS MANY AND MORPHS MEANS FORM
               POLYMORPHISM ALLOWS AN OBJECT TO TAKE ON MANY FORMS

TYPES OF POLYMORPHISM :
                 1) COMPILE TIME POLYMORPHISM/ STATIC POLYMORPHISM-----REFERS TO METHOD OVERLOADING 
AND CONSTRUCTOR OVERLOADING
                 2) RUN TIME POLYMORPHISM/ DYNAMIC POLYMORPHISM -------REFERS TO METHOD OVERRRIDING 



POLYMORPHISM IS A MECHANISM WHERE A PARENT CLASS REFERENCE VARIABLE CAN TAKE MANY FORMS (IT CAN REFER OBJECT 
FROM DIFFERENT CLASSES)

*/