package vid113To130;


    



/*
               
       LOCAL VARIABLE : A VARIABLE THAT IS DECLARED INSIDE THE METHOD CALLED LOCAL VARIABLE 
                        
                        LOCAL VARIABLE IS DECLARED INSIDE THE METHOD, CONSTRUCTOR OR IN A BLOCK;


       INSTANCE VARIABLE: A VARIABLE THAT IS DECLARED INSIDE THE CLASS BUT OUTSIDE ANY METHOD THAT IS CALLED INSTANCE VARIABLE
                          
                          IT IS  NOT DECLARED AS STATIC
       
        STATIC/CLASS VARIABLE: A VARIABLE THAT IS DECLARED AS STATIC IS CALLED STATIC VARIABLE OR CLASS VARIABLE

                               IT CAN'T BE DECLARED AS LOCAL VARIABLE






*/