



/*
        METHOD OVERLOADING IS A PROCESS THAT ALLOWS A CLASS TO HAVE TWO OR MORE METHODS HAVING SAME NAME,
        AS LONG AS THEIR PARAMETER DECLARATIONS ARE DIFFERENT

        THESE METHODS ARE CALLED OVERLOADED METHOD



POINTS TO REMEMBER ABOUT METHOD OVERLOADING
                               1. SAME METHOD NAMES
                               2. PARAMETER LISTS ARE DIFFERENT
                               3. INSIDE THE SAME CLASS



*/