package vid113To130;

/*
                                          CALL BY VALUE

            >>> IN THE CASE OF CALL BY VALUE , THE VALUE IS COPIED TO A METHOD PARAMETER.
            >>> CHNAGES TO THAT FORMAL PARAMETER DOESN'T AFFECT THE ACTUAL PARAMETER
            >>> IN CALL-BY-VALUE ORIGINAL VALUE DOESN'T CHANGES




           1. IF WE CALL A METHOD BY PASSING A VALUE (PRIMITIVE DATA) THEN IT IS KNOWN AS CALL BY VALUE 
       
           2. THE VALUE IS COPIED TO A METHOD PARAMETER
       
           3.CHANGES TO THAT FORMAL PARAMETER DOESN'T AFFECT THE ACTUAL PARAMETER.
 
           4.IN CALL BY VALUE ORIGINAL VALUE DOESN'T CHANGES



                                

                                        CALL BY REFERENCE
           
            1. IF WE CALL A METHOD BY PASSING A REFERENCE TYPE DATA(OBJECT,STRING,ADDRESS ETC) THEN IT IS KNOWN AS CALL BY REFERENCE

            2. CHANGES TO THE FORMAL PARAMETER DOES AFFECT TO THE ACTUALL PARAMETER

            3. IN CALL BY REFERENCE ORIGINAL VALUE GETS CHANGES

*/
