/*
                              INHERITANCE
     

1)WHAT IS INHERITANCE?
INHERITANCE CAN BE DEFINED AS THE PROCESS WHERE ONE CLASS AQUIRES THE PROPERTIES
(METHODS AND FIELDS) OF ANOTHER.



2) WHY DO WE NEED INHERITANCE?
    |)   FOR CODE REUSABILITY
    ||)  FOR METHOD OVERRIDING
    |||) TO IMPLEMENT PARENT CHIELD RELATIONSHIP

                   TYPES OF INHERITANCE

1)SINGLE
IN THIS SORT OF INHERITANCE, ONE SUB CLASS INHERITS FROM ONE SUPERCLASS
PUBLIC CLASS A{
........
........
}

PUBLIC CLASS B EXTENDS A{
.......
.......
}


2)MULTI LEVEL
IN THIS SORT OF INHERITANCE,THE SUPER CLASS FOR ONE IS THE SUBCLASS FOR OTHER.

PUBLIC CLASS A {
.........
.........
}

PUBLIC CLASS B EXTENDS A [
.........
.........
}
 
PUBLIC CLASS C EXTENDS B{
.........
.........
}


3)HIERARCHICAL
IN THIS SORT OF INHERITANCE,MULTIPLE SUBCLASS DERIVED FROM SINGLE SUPERCLASS

PUBLIC CLASS A {
..........
..........
}

PUBLIC CLASS B EXTENDS A {
..........
..........
}

PUBLIC CLASS C EXTENDS A {
..........
..........
}



4)MULTIPLE

PUBLIC CLASS A {
..........
..........
}
PUBLIC CLASS B EXTENDS A {
..........
..........
}

PUBLIC CLASS C EXTENDS A {
..........
..........
}

PUBLIC CLASS D EXTENDS A,B {
..........
..........

}




WHY JAVA DOES NOT SUPPORT MULTIPLE INHERITANCE?
  --> BOTH CLASSES ARE IN THE SAME LEVEL WITH SAME PRIORITY. IF WE WANT TO USE FOO() METHOD THAT FROM D CLASS
OBJECT LEADS TO AMBIGUITY.
                               THIS IS CALLED DIAMOND PROBLEM
*/