/*
    DECLARING METHOD IN SUBCLASS WHICH IS ALREADY PRESENT IN SUPERCLASS IS KNOWN AS METHOD OVERRIDING

ADVANTAGES OF METHOD OVERRIDING:
                    1)CODE REUSE
                    2)ONE INTERFACE MULTIPLE IMPLEMENT
                    3) RUN TIME POLYMORSHISM




WHAT ARE THE RULES OF METHOD OVERRIDING:
                    1) NAME,SIGNATURE TYPE MUST BE SAME
                    2) IF A METHOD CAN'T BE INHERITED, THEN IT CAN'T BE OVERRIDDEN
                    3) A MEHTOD DECLARED AS FINAL OR STATIC CAN'T BE OVERRIDDEN
                    4) CONSTRUCTOR CAN'T BE OVERRIDDEN

CAN WE OVERRIDE STATIC METHOD?
  --> NO, STATIC METHOD CAN'T BE OVERRIDDEN. BECAUSE STATIC METHOD IS BOUND TO CLASS, ON THE OTHER HAND
      METHOD IS BOUND TO OBJECT



CAN WE OVERRIDE JAVA MAIN METHOD ?
 --> NO, BECAUSE MAIN CLASS IS A STATIC METHOD




*/