/*


SUPER KEYWORD IS USED TO REFER IMMEDIATE SUPER CLASS OBJECT

USES OF SUPER KEYWORD:
             1) IT IS USED TO CALL SUPER CLASS INSTANCE VARIABLE
             2) IT IS USED TO CALL SUPER CLASS METHOD(OVERRIDEN METHOD)
             3) IT IS USED TO CALL SUPER CLASS CONSTRUCTOR



*/