/*
                                             THIS KEYWORD

THIS KEYWORD IS USED TO REFER CURRENT CLASS OBJECT

USAGE OF THIS KEYWORD:
          1) REFER CURRENT CLASS INSTANCE VARIABLE
          2) IT CAN BE USED TO CALL CURRENT CLASS CONSTRUCTOR
          3) IT CAN BE USED TO CALL CURRENT CLASS METHOD
          4) IT CAN BE PASSED AS AN ARGUMENT IN THE METHOD ( EVENT HANDLING)






*/